### PR TITLE
Sixtyfour

### PR DESCRIPTION
**Pull request by jamesu**
Fixed the issue with the ActionMap properly.

Added some explicit casts to prevent compiler warnings. Also changed dStrlen to use U32 instead of dsize_t.

### CODE REVIEW

**Comment by lilligreen** [comment]
Thank you for the fixes. After the merge it compiled fine as a 64-bit app (release build) but it still crashes directly at startup. Here's part of the error report:

```
Process:         Torque2D [88129]
Path:            /Users/USER/Downloads/*/Torque2D.app/Contents/MacOS/Torque2D
Identifier:      com.garagegames.Torque2D
Version:         1.0 (1)
Code Type:       X86-64 (Native)
Parent Process:  launchd [141]
Responsible:     Torque2D [88129]

Date/Time:       2014-02-16 15:20:14.971 +0100
OS Version:      Mac OS X 10.9.1 (13B42)
Report Version:  11

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: EXC_I386_GPFLT

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.garagegames.Torque2D        0x0000000102dd0642 Dictionary::add(char const*) + 64 (consoleDictionary.cc:186)
1   com.garagegames.Torque2D        0x0000000102dd0cd7 Dictionary::setVariable(char const*, char const*) + 25 (consoleDictionary.cc:426)
2   com.garagegames.Torque2D        0x0000000102ddf4bd Con::init() + 142 (console.cc:848)
3   com.garagegames.Torque2D        0x0000000102de9ffa initializeLibraries() + 19 (defaultGame.cc:115)
4   com.garagegames.Torque2D        0x0000000102dea5b2 DefaultGame::mainInitialize(int, char const**) + 28 (defaultGame.cc:344)
5   com.garagegames.Torque2D        0x0000000102f065e0 -[osxPlatState initializeTorque2D] + 40 (platformOSX.mm:276)
6   com.garagegames.Torque2D        0x0000000102f06634 -[osxPlatState runTorque2D] + 22 (platformOSX.mm:297)
7   com.garagegames.Torque2D        0x0000000102f05eb8 -[AppDelegate applicationDidFinishLaunching:] + 256 (AppDelegate.mm:61)
```

**Comment by jamesu** [comment]
Hmm very odd, I can't seem to reproduce the crash here. Are you using a the standard game folder? Also what are the specs of your system? (e.g. memory)

**Comment by jamesu** [comment]
Ah, spotted something! Could you change the following line in that file

```
S32 HashPointer(StringTableEntry ptr)
```

and in console.h and simDictionary.cc:

```
extern S32 HashPointer(StringTableEntry ptr);
```

To "U32" instead of S32 and let me know if it fixes the problem.

**Comment by lilligreen** [comment]
Yes, that did the trick. Open and closed the app a dozen times and no more crashes. Thanks again!

**Comment by jamesu** [comment]
Okie. If you want to merge this in, don't forget to add that final change then. Good luck ;)

**Pull request merged**
